ALTER TABLE users
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
ADD COLUMN status_changed_at TIMESTAMP,
ADD COLUMN status_reason TEXT,
ADD CONSTRAINT chk_users_status
CHECK (status IN ('ACTIVE','PENDING','INACTIVE','SUSPENDED','BLOCKED'));